/*
 * Copyright (C) 2014 Hector Espert Pardo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package gui;

import javax.swing.JComboBox;
import objetos.Agenda;
import objetos.Dia;
import objetos.Fecha;
import utilidades.Ventanas;

/**
 *
 * @author alumno
 */
public class DDia extends javax.swing.JDialog {
    
    private Dia dia;
    
    private Agenda agenda;
    

    /**
     * Creates new form DDia
     */
    public DDia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        dia = null;
   
    }
    
    public static void preguntarDia(java.awt.Frame parent, boolean modal, Agenda agenda) {
        
        DDia dialog_dia = new DDia(parent, modal);
        
        dialog_dia.setAgenda(agenda);
        
        dialog_dia.setLocationRelativeTo(null);
        
        dialog_dia.setVisible(true);
         
        dialog_dia.dispose();
 
    }
    
    
    public void setAgenda(Agenda agenda) {
        
        this.agenda = agenda;
        
        actualizarComboBox();
        
        dia = this.agenda.getDiaAleatorio();
        
        getDatosDia(dia);
        
        cambiarComboBox(dia);
 
    }
    
    
    public  Agenda getAgenda() {
        
        return agenda;
    }
    
    private boolean actualizarComboBox() {
        
        int dias = agenda.getDias();
        
        if (dias > 0) {
            
            CBFechas.removeAllItems();
            
            for (int i = 0; i < dias; i++) {
                
                CBFechas.addItem(agenda.getDia(i));    
            } 
            
            return true;
        } else {
            return false;
        }
    }
    
    private void añadirAlComboBox(Dia dia) {
        
        if (!actualizarComboBox()) {
            
            CBFechas.removeAllItems();
        }
        
        CBFechas.addItem(dia);
        
        CBFechas.setSelectedItem(dia);
             
    }
    
    private void cambiarComboBox(Dia dia) {
        
        if (dia != null) {
            CBFechas.setSelectedItem(dia);
        }
        
        
        
    }
           
    
    

    
    private void selecionarDia() {
        
        
        Fecha fecha = null;
        
        if (dia != null) {
            fecha = dia.getFecha();
        }
        
        fecha = DFecha.preguntarFecha(null, true, fecha);
        
        if (fecha == null) {
            
        } else {
            dia = agenda.getDiaBy(fecha);
            
            if (dia == null) {
                dia = new Dia(fecha);
            }
            añadirAlComboBox(dia);
            
            getDatosDia(dia);
        }
        
  
    }
    
    private void getDatosDia(Dia dia) {
        
        if (dia != null && dia.hayDatosTemperatura()) {
            TFTemp.setText(String.valueOf(dia.getTemperatura().getCentigrados()));
        } else {  
            Ventanas.cleanTextFiel(TFTemp);
        }

        
    }
    
    private void getDiaComboBox(JComboBox  combobox) {
        
        
            Object dia_box = combobox.getSelectedItem();
            
//            if (dia_box != null && dia_box.getClass() == dia.getClass()) {
//            
//            }
        
        
    } 
    
    private void modificarTemperatura() {
        try {        
            dia.setTemperatura(Ventanas.textFieldToTemperatura(TFTemp));
        } catch (Exception ex) {
            Ventanas.error(rootPane, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFTemp = new javax.swing.JTextField();
        BTemperatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        CBFechas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BFecha.setText("Añadir fecha");
        BFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Temperatura Maxima:");

        TFTemp.setColumns(4);

        BTemperatura.setText("Cambiar Temperatura");
        BTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTemperaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Lluvia Maxima:");

        jTextField1.setColumns(4);

        jLabel3.setText("l/h");

        jLabel4.setText("ºC");

        jButton1.setText("Cambiar Lluvia");

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });

        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        CBFechas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No hay datos disponibles" }));
        CBFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BFecha)
                                .addGap(18, 18, 18)
                                .addComponent(CBFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TFTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(BTemperatura))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(BCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFecha)
                    .addComponent(CBFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BTemperatura))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAceptar)
                    .addComponent(BCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFechaActionPerformed
        selecionarDia();
    }//GEN-LAST:event_BFechaActionPerformed

    private void BTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTemperaturaActionPerformed
        //modificarTemperatura();
    }//GEN-LAST:event_BTemperaturaActionPerformed

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        
        agenda.añadirDia(dia);
        
        System.out.println(dia);
        
        this.setVisible(false);
    }//GEN-LAST:event_BAceptarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
  
        this.setVisible(false);
    }//GEN-LAST:event_BCancelarActionPerformed

    private void CBFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFechasActionPerformed
        
            
        
    }//GEN-LAST:event_CBFechasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DDia dialog = new DDia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BFecha;
    private javax.swing.JButton BTemperatura;
    private javax.swing.JComboBox CBFechas;
    private javax.swing.JTextField TFTemp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
