/*
 * Copyright (C) 2014 Hector Espert Pardo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import objetos.Temperatura;

/**
 *
 * @author alumno
 */
public class PTemperatura extends javax.swing.JPanel implements ActionListener{

    private Temperatura temperatura;
    
    /**
     * Creates new form PTemperatura
     */
    public PTemperatura() {
        initComponents();
        temperatura = new Temperatura();  
        TFTemperatura.setText(String.valueOf(temperatura.getkelvin()));
        BTemperatura.addActionListener(this);
    }

    public void setTemperatura(Temperatura temperatura) {
        this.temperatura = temperatura;
        
        
    }

    public Temperatura getTemperatura() {
        return temperatura;
    }
    
    public void setTemperatura(double temperatura) {
        TFTemperatura.setText(String.valueOf(temperatura)); 
        switch (BTemperatura.getActionCommand()) {
            case "celsius":
                this.temperatura.setKelvin(temperatura); ;
                break;
            case "fahren":
                this.temperatura.setCentigrados(temperatura);
                break;
            case "kelvin":
                this.temperatura.setFahrenheit(temperatura);
                break;
            
        }
        
        System.out.println(this.temperatura);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFTemperatura = new javax.swing.JTextField();
        BTemperatura = new javax.swing.JButton();

        TFTemperatura.setEditable(false);
        TFTemperatura.setColumns(5);

        BTemperatura.setText("ºK");
        BTemperatura.setActionCommand("celsius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTemperatura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTemperatura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTemperatura;
    private javax.swing.JTextField TFTemperatura;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "kelvin":
                BTemperatura.setText("ºK");
                BTemperatura.setActionCommand("celsius");
                TFTemperatura.setText(String.format("%.2f", temperatura.getkelvin()));
                break;
            case "celsius":
                BTemperatura.setText("ºC");
                BTemperatura.setActionCommand("fahren");
                TFTemperatura.setText(String.format("%.2f",temperatura.getCentigrados()));
                break;
            case "fahren":
                BTemperatura.setText(" F");
                BTemperatura.setActionCommand("kelvin");
                TFTemperatura.setText(String.format("%.2f",temperatura.getFahrenheit()));
                break;  
        }
    }

    
 
}
